from decouple import config

EMAIL_BACKEND = config('EMAIL_BACKEND')
# EMAIL_USE_SSL = config('EMAIL_USE_SSL')
# EMAIL_PORT = config('EMAIL_PORT')
# EMAIL_ADMINISTRATOR = config('EMAIL_ADMINISTRATOR')
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# EMAIL_SUPPORT = config('EMAIL_SUPPORT', cast=Csv())
# DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
# CONTACT_EMAIL = config('CONTACT_EMAIL')
# INVITE_HOST = config('INVITE_HOST')

