def name_country_eng_to_pt_br(country):

    counties = {
        "afghanistan": 'Afeganistão',
        "albania": 'Albânia',
        "algeria": 'Argélia',
            "andorra": 'Andorra',
            "angola": 'Angola',
            "argentina": 'Argentina',
            "armenia": 'Armênia',
            "australia": 'Austrália',
            "austria": 'Áustria',
            "azerbaijan": 'Azerbaijão',
            "bahamas": 'Bahamas',
            "bahrain": 'Barém',
            "bangladesh": 'Bangladesh',
            "barbados": 'Barbados',
            "belarus": 'Belarus',
            "belgium": 'Bélgica',
            "belize": 'Belize',
            "benin": 'Benin',
            "bhutan": 'Butão',
            "bolivia": 'Bolívia',
            "bosnia & herzegovina": 'Bósnia e Herzegovina',
            "botswana": 'Botsuana',
            "brazil": 'Brasil',
            'british virgin islands': "Ilhas Virgens Britânicas",
            "brunei": 'Brunei',
            "bulgaria": 'Bulgária',
            "burkina faso": 'Burkina',
            "burma": 'Birmânia',
            "burundi": 'Burundi',
            "cambodia": 'Camboja',
            "cameroon": 'Camarões',
            "canada": 'Canadá',
            "cape verde islands": 'Ilhas de Cabo Verde',
            "chad": 'Chade',
            'channel islands': "Canal da Mancha",
            'cayman islands': "Ilhas Cayman",
            "chile": 'Chile',
            "china": 'China',
            "colombia": 'Colômbia',
            "democratic republic of the congo": 'Congo',
            "costa rica": 'Costa Rica',
            "croatia": 'Croácia',
            "cuba": 'Cuba',
            "cyprus": 'Chipre',
            "czech republic": 'Rep. Checa',
            "denmark": 'Dinamarca',
            "djibouti": 'Djibuti',
            "dominica": 'Dominica',
            "dominican republic": 'Rep. Dominicana',
            "ecuador": 'Equador',
            "egypt": 'Egito',
            "el salvador": 'El Salvador',
            "england": 'Inglaterra',
            "eritrea": 'Eritréia',
            "estonia": 'Estônia',
            "ethiopia": 'Etiópia',
            "fiji": 'Fiji',
            "finland": 'Finlândia',
            "france": 'França',
            "gabon": 'Gabão',
            "gambia": 'Gâmbia',
            "georgia": 'Georgia',
            "germany": 'Alemanha',
            "ghana": 'Gana',
            "great britain": 'Grã Bretanha',
            "greece": 'Grécia',
            "grenada": 'Grenada',
            "guatemala": 'Guatemala',
            "guinea": 'Guiné',
            "guyana": 'Guiana',
            "haiti": 'Haiti',
            "holland": 'Holanda',
            "honduras": 'Honduras',
            "hungary": 'Hungria',
            "iceland": 'Islândia',
            "india": 'Índia',
            "indonesia": 'Indonésia',
            "iran": 'Irã',
            "iraq": 'Iraque',
            "ireland": 'Irlanda',
            "israel": 'Israel',
            "isle of man": 'Ilha de Man',
            "italy": 'Itália',
            "japan": 'Japão',
            "jordan": 'Jordânia',
            "kazakhstan": 'Cazaquistão',
            "kenya": 'Quênia',
            "korea": 'Coréia',
            "kuwait": 'Kuwait',
            "laos": 'Laos',
            "latvia": 'Letônia',
            "lebanon": 'Líbano',
            "liberia ": 'Libéria',
            "libya": 'Líbia',
            "liechtenstein": 'Liechtenstein',
            "lithuania": 'Lituânia',
            "luxenbourg": 'Luxemburgo',
            "macedonia": 'Macedônia',
            "madasgascar": 'Madasgascar',
            "malawi": 'Malawi',
            "malaysia": 'Malásia',
            "mali": 'Mali',
            "malta": 'Malta',
            "maldives": 'Ilhas Maldivas',
            "mauritania": 'Mauritânia',
            "mauritius": 'Maurício',
            "mexico": 'México',
            "moldova": 'Moldávia',
            "monaco": 'Mônaco',
            "mongolia": 'Mongólia',
            "montenegro": 'Montenegro',
            "morocco": 'Marrocos',
            "mozambique": 'Moçambique',
            "namibia": 'Namíbia',
            "new zealand ": 'Nova Zelândia',
            "nicaragua": 'Nicarágua',
            "niger": 'Níger',
            "nigeria": 'Nigéria',
            "north korea": 'Coreia do Norte',
            "norway": 'Noruega',
            "oman": 'Omã',
            "pakistan": 'Paquistão',
            'palestinian authority': "Palestiniana",
            "panama": 'Panamá',
            "papua new guinea": 'Papua Nova Guiné',
            "paraguay": 'Paraguai',
            "peru": 'Peru',
            "philippines": 'Filipinas',
            "poland": 'Polônia',
            "portugal": 'Portugal',
            "puerto rico": 'Porto Rico',
            "qatar": 'Catar',
            "romania": 'Romênia',
            "russia": 'Rússia',
            "rwanda": 'Ruanda',
            "saudi arabia": 'Arábia Saudita',
            "scotland": 'Escócia',
            "senegal": 'Senegal',
            "serbia": 'Sérvia',
            "seychelles": 'Seychelles',
            "sierra leone": 'Serra Leoa',
            "singapore": 'Cingapura',
            "slovakia": 'Eslováquia',
            "slovenia": 'Eslovênia',
            "solomon islands": 'Ilhas Salomão',
            "somalia": 'Somália',
            "south africa": 'África do Sul',
            "south korea": 'Coréia do Sul',
            "spain": 'Espanha',
            "sri lanka": 'Sri Lanka',
            "sudan": 'Sudão',
            "suriname": 'Suriname',
            "swaziland": 'Suazilândia',
            "sweden": 'Suécia',
            "switzerland": 'Suíça',
            "syria": 'Síria',
            "taiwan": 'Taiwan',
            "tanzania": 'Tanzânia',
            "thailand": 'Tailândia',
            "togo": 'Togo',
            "trinidad & tobago": 'Trindade e Tobago',
            "tunisia": 'Tunísia',
            "turkey": 'Turquia',
            "turkmenistan": 'Turcomenistão',
            'turks & caicos islands': "Turks e Caicos",
            "tuvalu": 'Tuvalu',
            "uganda": 'Uganda',
            "ukraine": 'Ucrânia',
            "united arab emirates": 'Emirados Árabes',
            "united kingdom": 'Reino Unido',
            "united states": 'Estados Unidos',
            "uruguay": 'Uruguai',
            "uzbekistan ": 'Uzbequistão',
            "vanuatu": 'Vanuatu',
            "vatican": 'Vaticano',
            "venezuela": 'Venezuela',
            "vietnam": 'Vietnã',
            "western samoa": 'Samoa Ocidental',
            "yemen ": 'Iémen',
            "yugoslavia ": 'Jugoslávia',
            "zaire": 'Zaire',
            "zambia": 'Zâmbia',
            "zimbabwe": 'Zimbábue',
    }

    try:
        key = country.lower()
        country = counties[key]

    except KeyError:
        pass

    return country


def name_country_pt_br_to_eng(country):


    counties = {
        'afeganistão': 'Afghanistan',
        'albânia': 'Albania',
        'argélia': 'Algeria',
        'andorra': 'Andorra',
        'angola': 'Angola',
        'argentina': 'Argentina',
        'armênia': 'Armenia',
        'austrália': 'Australia',
        'áustria': 'Austria',
        'azerbaijão': 'Azerbaijan',
        'bahamas': 'Bahamas',
        'barém': 'Bahrain',
        'bangladesh': 'Bangladesh',
        'barbados': 'Barbados',
        'belarus': 'Belarus',
        'bélgica': 'Belgium',
        'belize': 'Belize',
        'benin': 'Benin',
        'butão': 'Bhutan',
        'bolívia': 'Bolivia',
        'bósnia e herzegovina': 'Bosnia & Herzegovina',
        'botsuana': 'Botswana',
        'brasil': 'Brazil',
        'ilhas virgens britânicas': 'British Virgin Islands',
        'brunei': 'Brunei',
        'bulgária': 'Bulgaria',
        'burkina': 'Burkina Faso',
        'birmânia': 'Burma',
        'burundi': 'Burundi',
        'camboja': 'Cambodia',
        'camarões': 'Cameroon',
        'canadá': 'Canada',
        'ilhas de cabo verde': 'Cape Verde Islands',
        'chade': 'Chad',
        'canal da mancha': 'Channel Islands',
        'ilhas cayman': 'Cayman Islands',
        'chile': 'Chile',
        'china': 'China',
        'colômbia': 'Colombia',
        'congo': 'Democratic Republic of the Congo',
        'costa rica': 'Costa Rica',
        'croácia': 'Croatia',
        'cuba': 'Cuba',
        'chipre': 'Cyprus',
        'rep. checa': 'Czech Republic',
        'dinamarca': 'Denmark',
        'djibuti': 'Djibouti',
        'dominica': 'Dominica',
        'rep. dominicana': 'Dominican Republic',
        'equador': 'Ecuador',
        'egito': 'Egypt',
        'el salvador': 'El Salvador',
        'inglaterra': 'England',
        'eritréia': 'Eritrea',
        'estônia': 'Estonia',
        'etiópia': 'Ethiopia',
        'fiji': 'Fiji',
        'finlândia': 'Finland',
        'frança': 'France',
        'gabão': 'Gabon',
        'gâmbia': 'Gambia',
        'georgia': 'Georgia',
        'alemanha': 'Germany',
        'gana': 'Ghana',
        'grã bretanha': 'Great Britain',
        'grécia': 'Greece',
        'grenada': 'Grenada',
        'guatemala': 'Guatemala',
        'guiné': 'Guinea',
        'guiana': 'Guyana',
        'haiti': 'Haiti',
        'holanda': 'Holland',
        'honduras': 'Honduras',
        'hungria': 'Hungary',
        'islândia': 'Iceland',
        'índia': 'India',
        'indonésia': 'Indonesia',
        'irã': 'Iran',
        'iraque': 'Iraq',
        'irlanda': 'Ireland',
        'israel': 'Israel',
        'ilha de man': 'Isle of Man',
        'itália': 'Italy',
        'japão': 'Japan',
        'jordânia': 'Jordan',
        'cazaquistão': 'Kazakhstan',
        'quênia': 'Kenya',
        'coréia': 'Korea',
        'kuwait': 'Kuwait',
        'laos': 'Laos',
        'letônia': 'Latvia',
        'líbano': 'Lebanon',
        'libéria': 'Liberia ',
        'líbia': 'Libya',
        'liechtenstein': 'Liechtenstein',
        'lituânia': 'Lithuania',
        'luxemburgo': 'Luxenbourg',
        'macedônia': 'Macedonia',
        'madasgascar': 'Madasgascar',
        'malawi': 'Malawi',
        'malásia': 'Malaysia',
        'mali': 'Mali',
        'malta': 'Malta',
        'ilhas maldivas': 'Maldives',
        'mauritânia': 'Mauritania',
        'maurício': 'Mauritius',
        'méxico': 'Mexico',
        'moldávia': 'Moldova',
        'mônaco': 'Monaco',
        'mongólia': 'Mongolia',
        'montenegro': 'Montenegro',
        'marrocos': 'Morocco',
        'moçambique': 'Mozambique',
        'namíbia': 'Namibia',
        'nova zelândia': 'New Zealand',
        'nicarágua': 'Nicaragua',
        'níger': 'Niger',
        'nigéria': 'Nigeria',
        'coreia do norte': 'North Korea',
        'noruega': 'Norway',
        'omã': 'Oman',
        'paquistão': 'Pakistan',
        'palestiniana': 'Palestinian Authority',
        'panamá': 'Panama',
        'papua nova guiné': 'Papua New Guinea',
        'paraguai': 'Paraguay',
        'peru': 'Peru',
        'filipinas': 'Philippines',
        'polônia': 'Poland',
        'portugal': 'Portugal',
        'porto rico': 'Puerto Rico',
        'catar': 'Qatar',
        'romênia': 'Romania',
        'rússia': 'Russia',
        'ruanda': 'Rwanda',
        'arábia saudita': 'Saudi Arabia',
        'escócia': 'Scotland',
        'senegal': 'Senegal',
        'sérvia': 'Serbia',
        'seychelles': 'Seychelles',
        'serra leoa': 'Sierra Leone',
        'cingapura': 'Singapore',
        'eslováquia': 'Slovakia',
        'eslovênia': 'Slovenia',
        'ilhas salomão': 'Solomon Islands',
        'somália': 'Somalia',
        'áfrica do sul': 'South Africa',
        'coréia do sul': 'South Korea',
        'espanha': 'Spain',
        'sri lanka': 'Sri Lanka',
        'sudão': 'Sudan',
        'suriname': 'Suriname',
        'suazilândia': 'Swaziland',
        'suécia': 'Sweden',
        'suíça': 'Switzerland',
        'síria': 'Syria',
        'taiwan': 'Taiwan',
        'tanzânia': 'Tanzania',
        'tailândia': 'Thailand',
        'togo': 'Togo',
        'trindade e tobago': 'Trinidad & Tobago',
        'tunísia': 'Tunisia',
        'turquia': 'Turkey',
        'turcomenistão': 'Turkmenistan',
        'turks e caicos': 'Turks & Caicos Islands',
        'tuvalu': 'Tuvalu',
        'uganda': 'Uganda',
        'ucrânia': 'Ukraine',
        'emirados árabes': 'United Arab Emirates',
        'reino unido': 'United Kingdom',
        'estados unidos': 'United States',
        'uruguai': 'Uruguay',
        'uzbequistão': 'Uzbekistan ',
        'vanuatu': 'Vanuatu',
        'vaticano': 'Vatican',
        'venezuela': 'Venezuela',
        'vietnã': 'Vietnam',
        'samoa ocidental': 'Western Samoa',
        'iémen': 'Yemen ',
        'jugoslávia': 'Yugoslavia ',
        'zaire': 'Zaire',
        'zâmbia': 'Zambia',
        'zimbábue': 'Zimbabwe',
    }

    try:
        key = country.lower()
        country = counties[key]
    except KeyError:
        pass

    return country
